routes/web.php
<?php

Route::get('/', function () {
    return view('posts.index');
});

Route::resource('posts', 'PostController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'body', 'password',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('posts.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|min:3|max:191',
            'body' => 'min:2',
            'password' => 'required|min:6|max:191',
        ]);

        if ($request->has('body')) {
            Post::create([
                'name' => $request->request->get('name'),
                'body' => encrypt($request->request->get('body')),
                'password' => bcrypt($request->request->get('password')),
            ]);

            return 'Saved successfully.';
        } else {
            $post = Post::where('name', $request->request->get('name'))->firstOrFail();

            if (\Hash::check($request->request->get('password'), $post->password)) {
                return decrypt($post->body);
            } else {
                return 'Wrong password';
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        return view('posts.show', compact('post'));
    }
}

resources/views/posts/index.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Encryption</title>
</head>
<body>
<form action="{{ route('posts.store') }}">
    <div>
        Name: <input type="text" name="name" value="{{ old('name') }}">
    </div>
    <div>
        Wachtwoord: <input type="password" name="password">
    </div>
    <div>
        <p>
            Laat de tekst leeg als je een tekst wil ophalen. Als je een tekst invult wordt deze opgeslagen in de
            database via encryption.
        </p>
        Tekst: <textarea type="text" name="body">{{ old('name') }}</textarea>
    </div>
</form>
</body>
</html>